### PR TITLE
Fix date format

### PR DESCRIPTION
**Pull request by qsantos**
Hey, I was bothered with some inconsistencies in the formatting/parsing of dates so I had a go at fixing it. ISO 8601 looks like the best fit to avoid confusion.

I also did some other changes, so let me know what you think of them!

### CODE REVIEW

**Comment by bakkot** [comment]
Neat, thanks! The changes to the date input box make it significantly more obtrusive, though (two lines instead of one), and 'datetime-local' inputs cannot as easily be copy-pasted, which is a common use case; I'm not willing to make those particular changes.

Also, ISO-8601 is ugly. I'd like to stick with locale strings if possible. I should probably roll some custom formatting code, but this is a hard problem, and in general I'm going to prefer non-ugly options even if they are technically ambiguous.

As for the timezone correction... the reason I sort of punted on it is that comments use server time. The way you've done it in this PR, if you load the page, then click into and out of the input box without changing it, you'll get more or fewer comments marked as new (depending on your time zone). This is because the actual date strings from the server are not UTC, and are also not marked with a timezone. So applying the correction based on the client's timezone is incorrect.

I'm not actually sure what to do about this. The best thing, I guess, would be to assume that the server's always going to be on Eastern Standard, and apply the appropriate correction when parsing. Such a change now would cause people to miss five hours' of comments, which is bad, but I guess not the end of the world.

With the current method of doing things, at least the date is relatively correct: the time string matches the timestamp on comments, and moving it back an hour shows an hours' worth of additional comments. I'm not going to make changes do not have this property.

**Comment by qsantos** [comment]
> Neat, thanks! The changes to the date input box make it significantly more obtrusive, though (two lines instead of one), and 'datetime-local' inputs cannot as easily be copy-pasted, which is a common use case; I'm not willing to make those particular changes.

I have indeed not tested for copy-pasting with other than Firefox. I will do that when possible and report here. I agree this behavior implies removing that commit.

> Also, ISO-8601 is ugly. I'd like to stick with locale strings if possible. I should probably roll some custom formatting code, but this is a hard problem, and in general I'm going to prefer non-ugly options even if they are technically ambiguous.

The thing is that ISO-8601 is the least evil of all date formats. The current _status quo_ makes it so that the input is pre-filled with DD/MM/YYYY but expects MM/DD/YYYY. An alternative would be to pre-fill with the same format at that of the comments (“Month DD, YYYY at HH:XX A/PM”). Also, the "T" from ISO8601 can always be replaced by a space.

**Remark:** the seconds should probably be stripped as well, in particular in the pre-filled box; that would gain some space

> As for the timezone correction... the reason I sort of punted on it is that comments use server time. The way you've done it in this PR, if you load the page, then click into and out of the input box without changing it, you'll get more or fewer comments marked as new (depending on your time zone). This is because the actual date strings from the server are not UTC, and are also not marked with a timezone. So applying the correction based on the client's timezone is incorrect.
> 
> I'm not actually sure what to do about this. The best thing, I guess, would be to assume that the server's always going to be on Eastern Standard, and apply the appropriate correction when parsing. Such a change now would cause people to miss five hours' of comments, which is bad, but I guess not the end of the world.
> 
> With the current method of doing things, at least the date is relatively correct: the time string matches the timestamp on comments, and moving it back an hour shows an hours' worth of additional comments. I'm not going to make changes do not have this property.

I did encounter this issue, and fixed it by [canceling the local offset](https://github.com/bakkot/SlateStarComments/pull/6/files#diff-2868ff60d179bfe83256bbab025c38deR21). This way, Javascript just treats all dates like if they were at EST. This works very well with my timezone (CET); are you encountering the issue anyway?

**Comment by bakkot** [comment]
Tip for testing in other browsers (well, Chrome, in particular): you can make a user script of it by adding the following to the top of the file and naming it as 'something.user.js':

``` javascript
// ==UserScript==
// @name           SlateStarComments
// @namespace      http://www.github.com/bakkot
// @description    testing
// @match          http://slatestarcodex.com/*
// @version        0.1
// ==/UserScript==
```

Then drag to `chrome://extensions` to install, and adblock the original script. You can of course do this with Greasemonkey as well, on Firefox. (Actually I assume that's what you're already doing, in which case you probably didn't need this pointed out to you, but perhaps not.) 

## 

Same format as the comments is a decent idea, but they're a bit too verbose to fit well in the date input box. `.toISOString().replace('T', ' ').substr(0, 16)` is pretty reasonable, though, and I'd take that. It's pretty similar to what you get with Chrome and Firefox anyway.

Unfortunately, Firefox can't parse dates in that format: `Date.parse((new Date).toISOString().replace('T',' ').substring(0,16)); // NaN`. They'll need to be corrected back. [Line 158](https://github.com/qsantos/SlateStarComments/blob/gh-pages/ssc.js#L158), instead of being _fromHuman (which is really only for blog-provided timestamps anyway), should be something like `Date.parse(dateInput.value.replace(' ', 'T')+':00.000Z')`.

## 

I could swear I saw the behavior I described when I was testing earlier (i.e., clicking in and out causes more comments to be highlighted), but now I can't reproduce. Not sure what that's about. Hopefully just my eyes playing tricks on me, not nondeterminism.

Your timezone fix treats all dates as _UTC_, though, surely, not EST. Which is as it should be.

## 

I can't commit and test right now, but will take another look in the morning.

**Comment by qsantos** [comment]
> Tip for testing in other browsers (well, Chrome, in particular): you can make a user script of it by adding the following to the top of the file and naming it as 'something.user.js':
> 
> ```
> // ==UserScript==
> // @name           SlateStarComments
> // @namespace      http://www.github.com/bakkot
> // @description    testing
> // @match          http://slatestarcodex.com/*
> // @version        0.1
> // ==/UserScript==
> ```
> 
> Then drag to chrome://extensions to install, and adblock the original script. You can of course do this with Greasemonkey as well, on Firefox. (Actually I assume that's what you're already doing, in which case you probably didn't need this pointed out to you, but perhaps not.) 

I had… not thought about that at all. I just grabbed a comment page, changed the `<script>` tag for `ssc.js` and ran a webserver with `python3 -m http.server`. User scripts with a few symbolic links and a script blocker (to disable the deployed one) are perfect! I am very grateful for that tip, thanks a bunch!

> Same format as the comments is a decent idea, but they're a bit too verbose to fit well in the date input box. .toISOString().replace('T', ' ').substr(0, 16) is pretty reasonable, though, and I'd take that. It's pretty similar to what you get with Chrome and Firefox anyway.
> 
> Unfortunately, Firefox can't parse dates in that format: Date.parse((new Date).toISOString().replace('T',' ').substring(0,16)); // NaN. They'll need to be corrected back. Line 158, instead of being _fromHuman (which is really only for blog-provided timestamps anyway), should be something like Date.parse(dateInput.value.replace(' ', 'T')+':00.000Z').

Gotcha. Just, the "Z" should not be added back, since `time_toHuman()` gives a localized time. This is because `time_fromHuman()` expects a localized time when being fed the posts' dates, which itself is due to `Date.parse()`.

> I could swear I saw the behavior I described when I was testing earlier (i.e., clicking in and out causes more comments to be highlighted), but now I can't reproduce. Not sure what that's about. Hopefully just my eyes playing tricks on me, not nondeterminism.

Guess: date from currently deployed script was in localStorage, with local timezone

> Your timezone fix treats all dates as UTC, though, surely, not EST. Which is as it should be.

Yeah, I was not really clear with this. I meant that Javascript is “thinking” it is UTC, while it “really” is EST.

---

Changes to the PR:
- more readable ISO 8601 format (@7c810eb)
- a few more tweaks for medium and small screens (@d182f6c)
- `[+]` becomes `[ ‑ ]` (non-breaking hyphen and non-breaking spaces, which seems to render well) when the list is expanded (new @ae200ff)

**Comment by bakkot** [comment]
Omitting the 'Z' does not accomplish the correct thing on Chrome or Safari, which apparently assume its presence. The problem is that Date.parse only has [defined behavior](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.4.2) for [one specific format](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15). See [this jsfiddle](http://jsfiddle.net/bakkot/kjxqd1ce/) in non-Firefox browsers. 

I think `fromComment`, `fromInput`, and `toInput` from that fiddle are the correct functions to use.

## 

wrt aesthetic changes: I would prefer to omit the spaces from `[ - ]`, so its size doesn't change. (As written, at least on Chrome, it expands and overflows the box).

Otherwise seems solid. I lack a sufficiently small screen to test properly.

## 

Aside: this should maybe have been two different PRs; one for aesthetic changes, and one for the date formatting and parsing. Doesn't really matter, though, and isn't worth modifying.

**Comment by qsantos** [comment]
> Omitting the 'Z' does not accomplish the correct thing on Chrome or Safari, which apparently assume its presence. The problem is that Date.parse only has defined behavior for one specific format. See this jsfiddle in non-Firefox browsers.

Nice catch.

> I think `fromComment`, `fromInput`, and `toInput` from that fiddle are the correct functions to use.

I do like having only two functions `time_fromHuman` and `time_toHuman` to handle the date and not having to worry about it in the rest of the code. It does `time_fromHuman` uglier than `fromComment` and `fromInput` though. It is `time_fromHuman` in the current version. Do you have a preference for the other style?

> wrt aesthetic changes: I would prefer to omit the spaces from [ - ], so its size doesn't change. (As written, at least on Chrome, it expands and overflows the box).

i will look at that.

> Otherwise seems solid. I lack a sufficiently small screen to test properly.

`Ctrl+Shift+M` on Firefox gives pretty good approximations.

---

> Aside: this should maybe have been two different PRs; one for aesthetic changes, and one for the date formatting and parsing. Doesn't really matter, though, and isn't worth modifying.

Agreed, it was just too tempting. I moved the commit to a local branch so I will take the time to think about it separately.

**Comment by qsantos** [comment]
Bump, just in case you forgot about this PR ;) .

**Comment by bakkot** [comment]
Didn't forget, just got caught up with exams! I might hold off on actually releasing it until the next open thread, though, so that people who do not know that the script lives here have an obvious place to report bugs.

**Comment by qsantos** [comment]
Nice way to locate bug reports!

I have a few other pending commits, mainly for keyboard navigation, and nicer reading. Should we wait for after OT25 before considering pushing further changes?

**Comment by bakkot** [comment]
Eh, might as well do 'em all at once. Put those in another PR, though, if you can.

**Comment by bakkot** [comment]
Too late [now](http://slatestarcodex.com/2015/12/12/ot37-one-horse-open-sleigh/#comment-280907)! But if you open a new PR with any other changes I'll see about getting them merged in for the next one.

**Pull request merged**
